services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - auth-service
  auth-service:
    container_name: ${AUTH_NAME}
    restart: always
    build:
      context: ./${AUTH_NAME}
      args:
        PORT: ${AUTH_PORT}
        NAME: ${AUTH_NAME}
    env_file:
      - .env
    environment:
      - DB_CONTAINER_NAME=${DB_NAME}
      - PORT=${AUTH_PORT}
      - NAME=${AUTH_NAME}
    ports:
      - ${AUTH_PORT}:${AUTH_PORT}
    volumes:
      - ./${AUTH_NAME}:/${AUTH_NAME}
      - /${AUTH_NAME}/node_modules
    depends_on:
      - mongo
      - user-service
  user-service:
    container_name: ${USER_NAME}
    restart: always
    build:
      context: ./${USER_NAME}
      args:
        PORT: ${USER_PORT}
        NAME: ${USER_NAME}
    env_file:
      - .env
    environment:
      - DB_CONTAINER_NAME=${DB_NAME}
      - PORT=${USER_PORT}
      - NAME=${USER_NAME}
    ports:
      - ${USER_PORT}:${USER_PORT}
    volumes:
      - ./${USER_NAME}:/${USER_NAME}
    depends_on:
      - mongo
  mongo:
    container_name: ${DB_NAME}
    restart: always
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./mongo_data:/data/db